### ISSUE TITLE
Refactor codebase to use one consistant function notation

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1531]
In some places, we define functions using es6 syntax. in others, we don't. In some scripts we will use both formatting styles in the same file! this should be made to be consistent throughout the repo.

**Comment by mrice32** [comment]
The various function declarations are different in some subtle ways: see [this article](https://dmitripavlutin.com/6-ways-to-declare-javascript-functions/). IMO, we should use the following simple rules:
1. Use "normal" (old school) function declarations when the function is named and declared at the file-level or class-level scope.
2. Use "arrow" functions when declaring a function within another function/some tighter scope or when the function is anonymous.

The reason I suggest this is:
1. IMO, this makes usage of `this` more intuitive. When declaring a function inline within some other function, it just inherits `this` from the outer function's context (arrow function case), but when declaring it at the file-level scope, there is no `this` to inherit, so the this is implicitly the function's `this`.
2. IMO, hoisting is intuitive when done at the file-level or class-level scope (this is very common in other languages) because you'd expect the function order to not matter in that context. But it feels pretty unnatural when done inside other functions or tighter scopes because it feels more variable-like, and hoisting would allow it to be referenced/called before its declaration.


I also feel like this style is pretty idiomatic in javascript, from what I've seen. Thoughts?

**Comment by chrismaree** [comment]
I think this is a good rule of thumb. Looking through the code base this will be a rather large PR with some pretty big churn. I'm going to look for a tool to do this for us, if possible.
