### ISSUE TITLE
Update deployment address information in docs

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1652]
The main net deployment addresses & identifiers currently out of date. for example:
https://docs.umaproject.org/uma/oracle/mainnet_deployment_info.html
https://docs.umaproject.org/uma/developer_reference/contract_addresses.html

These should be updated to the latest information.

**Comment by adrianmcli** [comment]
Oh wow, I think these params should really be on a dashboard where we can refer users to. But barring that, I can update the numbers and add an "updated at" timestamp so people are aware of how current the info is.

@chrismaree For the contract addresses, shouldn't it be current because it references the `json` files in the `networks` folder?

**Comment by chrismaree** [comment]
ye, this sounds good to point to that file. However, some sections like this one could be manually updated for now:
![image](https://user-images.githubusercontent.com/12886084/85852534-148b7680-b7b1-11ea-9aa8-2d6a5575c09e.png)

In the future, it would be really sweet to have an `tools.umaproject.org` that had all this kind of information automatically pulled from the contracts and always up to date.
