### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by daywiss** [UMAprotocol/protocol#1781]
I think this would be useful to add, either as its own section or as addendum to the style guide, but just like a general format to follow when doing certain things like:
- creating issues, whether its a bug, a feature or a task and the context necessary for resolving that
- creating prs, best practices for formatting commit messages, merge rule ( rebase vs merge), branch naming convention, issue linking, and anything else
- or just explicitly saying there are no real rules just do what you think is best, which is perfectly valid

I am personally not very opinionated on this but I would feel better if I knew that there were either no rules, are there are certain guidelines to follow. 
As velocity grows, it may be useful to think about things like:
- bug requests should include why its considered a bug, steps to replicate issue, version numbers if relevant
- tasks should include context around the task, implementation notes and resolution criteria
- maybe commits can follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) with the future thought of auto versioning and continuous deployment
- meta changes and major changes to codebase could be discussed in a structured way using ["request for comments"](https://www.ietf.org/rfc/rfc2119.txt)

**Comment by daywiss** [comment]
i really like reacts contributing page: https://reactjs.org/docs/how-to-contribute.html
It reads like a tutorial for both internal or external contributors, which is great and theres a lot we could take from that.

**Comment by mrice32** [comment]
> i really like reacts contributing page: https://reactjs.org/docs/how-to-contribute.html
> It reads like a tutorial for both internal or external contributors, which is great and theres a lot we could take from that.

I agree -- it's really nice, and it also happens to match our intention of using releases to handle versioning and keeping a single protected branch that you merge to (`master`) rather than having `develop` or `staging` branches, etc.

Do you think our contributing guidelines should be linked in the readme or put somewhere more prominent, like our docs site?

**Comment by daywiss** [comment]
> I agree -- it's really nice, and it also happens to match our intention of using releases to handle versioning and keeping a single protected branch that you merge to (master) rather than having develop or staging branches, etc.

Interesting, i didnt think about those mechanics, but that is cool.

I think that its fine just linked in the readme, i see this more as a benefit for us internally and onboarding.  It seems like if we link all the stuff first in the repos readme it makes it easy to find for devs, as I can just go to the uma protocol repo to find everything i need.  Its lower priority to get it visible to the rest of the community imo.

**Comment by mrice32** [comment]
> creating prs, best practices for formatting commit messages, merge rule ( rebase vs merge), branch naming convention, issue linking, and anything else

I think some of this can be set up in the PR template, but a few of these should just be documented somewhere so we can point at it when needed.

A few things I'd also like to include in these guidelines:
- There are some embedded "rules" in our repo around who needs to approve and how it gets decided who needs to approve.
- We generally let maintainers (anyone on the UMA team) merge their own PRs after approval rather than someone else on the team merging for them, just because they know when things are _done_ and they've gotten all the reviews they wanted.

> or just explicitly saying there are no real rules just do what you think is best, which is perfectly valid

It's interesting because there _are_ rules, but they are basically just convention. They aren't documented or really enforced. We should document them.

> maybe commits can follow conventional commits with the future thought of auto versioning and continuous deployment

Never seen conventional commits before, but I generally like the idea -- we may modify it a bit and steal it :).

> meta changes and major changes to codebase could be discussed in a structured way using "request for comments"

Yeah, I think having an RFC setup could make sense, but I might propose that it be a bit lighter weight than a separate repo. I think either having an issue template that can be used to write an RFC or having people link comment-able google docs might be a little simpler. I mostly say this because GH's review interface isn't the best for reviewing long-form, complex, collaborative writing.
