### ISSUE TITLE
Liquidator bot defaults to crazy high gas limits

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1791]
**Description**

When a bot creates a liquidation it defaults to 9 million gas. This is very inefficient.
see: https://discordapp.com/channels/718590743446290492/736828585809281094/738812451239231609

**Reproduction**

Create a liquidation from a bot and see the gas limit.

**Expected Behavior**

Gas limit should not be 9 million.

**Screenshots**

![image](https://user-images.githubusercontent.com/12886084/89062183-4a022180-d366-11ea-8d4c-ca72a9ead575.png)

**Comment by mrice32** [comment]
I think I've figured out why this happens. Truffle contract instantiations do gas estimation automatically as long as the default gas limit is `undefined` (as it is in our config). However, the liquidator uses a `web3` instantiations, so the gas limit isn't done automatically. I think the choices are basically:
1. Do the gas estimation manually (using `.estimateGas()`).
2. Write a function that does the gas estimation and sends the txn automatically, so gas estimates can be employed for all of our web3 contract instantiations.
3. Use a truffle instantiation here rather than web3.

**Comment by chrismaree** [comment]
I have implemented solution 1 as it is the simplest and cleanest. In the future, I think we should use solution 2 by creating a simple transaction handler that deals with gas estimation and gas increases in times of congestion using @kendricktan gas estimator package.
