### ISSUE TITLE
Reorganize umips scripts directory in core

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#2006]
**Why**

Right now the core's scripts directory is a bit all over the place. We refer to some UMIP upgrades as `UMIP-3`, & `UMIP-8` but others are `creator-umip`. Additionally, some UMIPs use the same script (partially the `2_VoteSimulate.js` is common. This should be cleaned up.

**How**

Move all UMIP scripts to an UMIPs directory within scripts. Re-name the all directories to follow the same convention. Pull vote simulate out into a separate `common` directory and re-use this logic within the UMIP directories.

**Resolution**

UMIPs are better organized.

**Difficulty Score [1-10]**

- 3: ~1 hour

**Comment by daywiss** [comment]
> is there a pattern we want to consider to enable us to re-use these scripts more effectively? right now we have a bunch of sim links but there might be a better layout for this.

I think I've worked the least with these scripts but here are some thoughts:

I do think using these symlinks in general is annoying, it causes confusion on the dev and causes confusion in the tooling ( at least with my setup).  Rather than symlinks, I'm pretty sure you can just create a js file which its only job is to `require` the other file. Not much better, but at least symlinks are gone. 

The next lowest lift here would be to pull out the vote simulate file to work across all the scripts, like what you are suggesting chris. There's a copy of this file in umip-15 and umip-3 which is pretty confusing. Recent changes to the umip-3 file in #2302 brings it very close to the file in umip-15.  If its possible to reconcile differences and make this one file work for all the scripts that would be nice, and then pull it out as a shared dependency.

Next would be to refactor the scripts in such a way that the functionality is separate from the umip configuration. These scripts seem like they were originally intended to be re-written and almost hard coded for each new umip, but in the process a lot of common themes were discovered and previous work was reused. Ideally we would want to abstract the scripts in such a way where they could be named based on what they do rather than what umip they did work for, and provide configuration variables to run for a specific umip.  Not clear to me how much work this is and if effort to payoff is worth it though.
