### ISSUE TITLE
Funding Rate Store: Add Mechanism for distributing rewards to funding rate proposers

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#2039]
**Why**

Project Evergreen.

**Difficulty Score [1-10]**

- 5: ~4 hours

**Comment by nicholaspai** [comment]
### Motivation
It is undecided currently how rewards should work in the Funding Rate Store. The Store can use rewards and penalties to incentivize "proposers" to report the correct funding rate. We need to first determine what the cost of an incorrect funding rate is.

### Proposal Bond
Let's determine the size of a funding rate proposal bond. This is the "penalty" that a dishonest proposer forfeits if they propose an incorrect funding rate. Whenever a funding rate is incorrect, an error occurs in which the contract's reported total debt outstanding deviates from its correct value. Seen from another light, this "error" is equivalent to a someone's potential profit.

In summary: The funding rates reported by the Store are used to **secure the value in the PerpetualContract**. **Therefore, the cost to corrupt the funding rate should exceed the potential profit from corruption of the funding rate.** What affects the potential profit from corruption?

- This `PfC` or error  compounds over time because it is applied as a % of the contract's total debt `D`. For example, imagine the funding rate is off by `X`% for `S` seconds, then after `S` seconds, `D` displays an error of `(D * X)^S`
- Every unit time's `PfC` is proportional to the magnitude between the latest funding rate (i.e. whatever `store.getCurrentFundingRate()` returns) and the true funding rate. If the latest funding rate is 1%/second, and true funding rate is 5%/second, then the `PfC` of `X` is 4%/second.

Let's make some assumptions and put conservative numbers on the `PfC`:
- First of all, let's make an assumption about the maximum absolute `rate` that can be charged. Let's say that the `rate` cannot be higher/lower than the equivalent of 360%/year. In other words, if the maximum `rate` is set and unchanged, then the contract will pay out all of its collateral in 100 days. 
- How long can a funding rate be incorrect for? Assuming a proposer liveness period of 2 hours, a funding rate can only be incorrect for 2 hours. Let's say the current funding rate is incorrect, and an honest proposer submits a new funding rate. Right before the 2 hours expire, a dishonest person (who is incentivized to keep the funding rate unchanged) disputes the proposed funding rate and pays a dispute bond. This deletes the pending funding rate, and the honest proposer can again submit a new funding rate. **Clearly the value of the dispute bond needs to be higher than the profit earned from 2 hours of an incorrect funding rate.**
- The maximum funding rate of 360%/year translates to 1%/day => 0.083%/2 hours. But, the highest magnitude that the funding rate can change is actually 360%/year * 2, if the current funding rate is -360%/year and the true rate is +360%/year. So, the profit from corruption is 0.083%/2 hours * 2 = 0.167%/2 hours.

There's a problem here: this is a really high `PfC` value. Imagine a contract with $10 million of locked collateral. This would imply a `PfC` of 0.00167 * $10 million = $16,700. The funding rate proposal bond would have to be > $16,700, which is a large notional value. 

### Proposal Reward
The proposal reward incentivizes honest proposers to report correct funding rates. The net reward for (proposing a funding rate + disputing your own proposal) should be < 0 to prevent proposers from purposefully proposing false funding rates and disputing themselves and earning a round-trip arbitrage. **Let's assume that the proposal bond is equal to the dispute bond. So, the proposal bond has to be greater than the proposal reward.** 

First of all, how should the Funding Rate Store acquire a treasury with which to pay rewards?
- The current thinking here is tax the PerpetualContract similar to a regular fee.

Secondly, assuming that the Store has some amount of treasury with which to pay rewards, what are its goals? I believe that the goal of the Store should be to reduce the amount of funding rate error (equivalent to `PfC`). As explained above, funding rate error compounds over time and is proportional to the magnitude of latest-versus-true funding rates. Therefore, one design for computing the size of rewards is:
- Every successful proposer can earn up to `Q * M` of the Store's treasury `T`.
- `M` is proportional to the magnitude of latest-versus-true funding rates and is between [0, 1]
- `Q` is an amount < `T / C` such that the maximum amount the treasury pays out for any given proposer is `1 / C` of `T`. 

Putting example numbers on this:
- Let's say the magnitude of latest-versus-true funding rates is 0.7 (i.e. the true funding rate is 10x greater/less than the latest funding rate, and this translates into an `M = 0.7`)
- `Q` is  0.10 (i.e. A maximum of 10% of the treasury is paid out for any given proposer).
- `T = $100`
- A proposer can earn rewards of `$100 * 0.10 * 0.7 = $7`. If the magnitude were even larger, then `M` would approach 1 and the proposer rewards would approach $10.

How does this reward formula compare to `PfC`? Ideally, it should "scale" with `PfC` meaning that the incentive to report a correct rate should increase as `PfC` increases:
- `PfC` increases the longer the funding rate is incorrect. This reward increases the longer the funding rate is incorrect because `T` increases over time (remember, it is charged like a regular fee).
- `PfC` increases the larger the delta of the latest funding rate, this is captured by the `M` component of the formula.

**Comment by nicholaspai** [comment]
> ### Motivation
> It is undecided currently how rewards should work in the Funding Rate Store. The Store can use rewards and penalties to incentivize "proposers" to report the correct funding rate. We need to first determine what the cost of an incorrect funding rate is.
> 
> ### Proposal Bond
> Let's determine the size of a funding rate proposal bond. This is the "penalty" that a dishonest proposer forfeits if they propose an incorrect funding rate. Whenever a funding rate is incorrect, an error occurs in which the contract's reported total debt outstanding deviates from its correct value. Seen from another light, this "error" is equivalent to a someone's potential profit.
> 
> In summary: The funding rates reported by the Store are used to **secure the value in the PerpetualContract**. **Therefore, the cost to corrupt the funding rate should exceed the potential profit from corruption of the funding rate.** What affects the potential profit from corruption?
> 
> * This `PfC` or error  compounds over time because it is applied as a % of the contract's total debt `D`. For example, imagine the funding rate is off by `X`% for `S` seconds, then after `S` seconds, `D` displays an error of `(D * X)^S`
> * Every unit time's `PfC` is proportional to the magnitude between the latest funding rate (i.e. whatever `store.getCurrentFundingRate()` returns) and the true funding rate. If the latest funding rate is 1%/second, and true funding rate is 5%/second, then the `PfC` of `X` is 4%/second.
> 
> Let's make some assumptions and put conservative numbers on the `PfC`:
> 
> * First of all, let's make an assumption about the maximum absolute `rate` that can be charged. Let's say that the `rate` cannot be higher/lower than the equivalent of 360%/year. In other words, if the maximum `rate` is set and unchanged, then the contract will pay out all of its collateral in 100 days.
> * How long can a funding rate be incorrect for? Assuming a proposer liveness period of 2 hours, a funding rate can only be incorrect for 2 hours. Let's say the current funding rate is incorrect, and an honest proposer submits a new funding rate. Right before the 2 hours expire, a dishonest person (who is incentivized to keep the funding rate unchanged) disputes the proposed funding rate and pays a dispute bond. This deletes the pending funding rate, and the honest proposer can again submit a new funding rate. **Clearly the value of the dispute bond needs to be higher than the profit earned from 2 hours of an incorrect funding rate.**
> * The maximum funding rate of 360%/year translates to 1%/day => 0.083%/2 hours. But, the highest magnitude that the funding rate can change is actually 360%/year * 2, if the current funding rate is -360%/year and the true rate is +360%/year. So, the profit from corruption is 0.083%/2 hours * 2 = 0.167%/2 hours.
> 
> There's a problem here: this is a really high `PfC` value. Imagine a contract with $10 million of locked collateral. This would imply a `PfC` of 0.00167 * $10 million = $16,700. The funding rate proposal bond would have to be > $16,700, which is a large notional value.
> 
> ### Proposal Reward
> The proposal reward incentivizes honest proposers to report correct funding rates. The net reward for (proposing a funding rate + disputing your own proposal) should be < 0 to prevent proposers from purposefully proposing false funding rates and disputing themselves and earning a round-trip arbitrage. **Let's assume that the proposal bond is equal to the dispute bond. So, the proposal bond has to be greater than the proposal reward.**
> 
> First of all, how should the Funding Rate Store acquire a treasury with which to pay rewards?
> 
> * The current thinking here is tax the PerpetualContract similar to a regular fee.
> 
> Secondly, assuming that the Store has some amount of treasury with which to pay rewards, what are its goals? I believe that the goal of the Store should be to reduce the amount of funding rate error (equivalent to `PfC`). As explained above, funding rate error compounds over time and is proportional to the magnitude of latest-versus-true funding rates. Therefore, one design for computing the size of rewards is:
> 
> * Every successful proposer can earn up to `Q * M` of the Store's treasury `T`.
> * `M` is proportional to the magnitude of latest-versus-true funding rates and is between [0, 1]
> * `Q` is an amount < `T / C` such that the maximum amount the treasury pays out for any given proposer is `1 / C` of `T`.
> 
> Putting example numbers on this:
> 
> * Let's say the magnitude of latest-versus-true funding rates is 0.7 (i.e. the true funding rate is 10x greater/less than the latest funding rate, and this translates into an `M = 0.7`)
> * `Q` is  0.10 (i.e. A maximum of 10% of the treasury is paid out for any given proposer).
> * `T = $100`
> * A proposer can earn rewards of `$100 * 0.10 * 0.7 = $7`. If the magnitude were even larger, then `M` would approach 1 and the proposer rewards would approach $10.
> 
> How does this reward formula compare to `PfC`? Ideally, it should "scale" with `PfC` meaning that the incentive to report a correct rate should increase as `PfC` increases:
> 
> * `PfC` increases the longer the funding rate is incorrect. This reward increases the longer the funding rate is incorrect because `T` increases over time (remember, it is charged like a regular fee).
> * `PfC` increases the larger the delta of the latest funding rate, this is captured by the `M` component of the formula.

**Comment by nicholaspai** [comment]
After a discussion with @chrismaree we came up with some clarifications and optimizations:

Q1: How do I arrive at this assumption:
> First of all, let's make an assumption about the maximum absolute rate that can be charged. Let's say that the rate cannot be higher/lower than the equivalent of **360%/year**. In other words, if the maximum rate is set and unchanged, then the contract will pay out all of its collateral in 100 days.

- This is based on perpetual swap funding rate history data from [Bitmex](https://www.bitmex.com/app/fundingHistory?start=0) and [Skew.com](https://analytics.skew.com/dashboard/bitcoin-futures). The 8h funding rate rarely goes as high as 0.1% and sustains there. 0.1% / 8h is approximately `(0.001 * 3 * 360) = 108%` per year, and 360% was just taken as a multiple of that that is also a round number easily divisible by 360 days in a year.

Q2: Is this assumption fair?
- I think we can safely set the max funding rate assumption to 200%/year, implying a sustained "extremely high" funding rate for an entire year, which would be a very unlikely occurrence.

Q3: Should we constrain the funding rate in the contract to bound the PfC?
- I think yes, we should. If we set a range of funding rates allowed to be set by the store to the equivalent of +/- 200%/year, then we can bound the PfC and therefore bound the proposer bond amount.

Q4: How much of the proposer bond should be slashed if a proposer is incorrect?
- 100% seems harsh and additionally does not accurately reflect the CoC of a dishonest proposer. Let's say that the proposer proposes a pending funding rate of 0.1%, but they get disputed and it turns out that the true funding rate is 0.05%. If the dishonest proposer had not been disputed, then they would have introduced only (0.1 - 0.05)% corruption into the store, not the full CoC based on the maximum funding rate change. We can therefore reduce the CoC (and the risk) to proposers by only slashing their proposal bonds by the % that their proposed funding rate is incorrect.

Q5: Should the CoC/proposal bond calculation be variable?
- Imagine that the funding rate currently is 0.01% and the maximum allowed is +/- 0.2%. The previous CoC calculation assumes a maximum funding rate change of `(2 * 0.2% = 0.4%)`, which would be a swing from -0.2% to +0.2%. However, with the current funding rate at +0.01%, the maximum change is actually only `(0.01% + 0.2%) = 0.21%`. So, we can make the proposal bond a function of the current funding rate: `propose-bond = absolute_value(current_rate) + maximum_rate_allowed)`

Q6: Using real numbers, what is a potential CoC now for a $10million contract?
- Assuming a maximum funding rate of 200%/year, or `(200/360/12) = 0.046%`/2hours, the maximum proposal bond is `0.0046 * $10mil = $4600`. Recall from Q5 that the proposal bond is computed using a funding rate equal to the absolute value of the current rate plus the max funding rate. Therefore, if the current funding rate is at the maximum/minimum of +/- 200%/year, then the proposal bond would use a funding rate of 200%/year plus 200%/year (i.e. the funding rate theoretically could swing from +200%/year to -200%/year). This would imply a proposal bond of $9200. But, in most cases, the funding rate would be somewhere between +/- 100%/year which would mean that the proposal bond would usually be less than 1.5 * $4600 = $6900.

Q7: What if Funding Rate Store's treasury gets too large because the funding rate is not getting updated enough?
- We can parameterize a maximum treasury amount for the Store such that whenever it has excess treasury over the max, it can send back funds to the contract.

Q8: How should we determine the % rate at which the Perpetual sends funds to the Funding Rate Store?
- This should ideally be modifiable from either the Perpetual or the Store contract's point of view, but in the future we could also make it variable. Theoretically the rate should be higher when there have historically been more funding rate updates, so the Store could keep a counter of how many updates it has seen, and divide that by its lifespan to get a very rough moving average of its update rate. This could be used to modify its tax rate on the Perpetual.

Q9: How should funding rate disputer bonds and rewards be determined?
- Let's think about what the disputer's CoC is. If a disputer is dishonest, then they are blocking a valid funding rate from being published. In the worst case this would delay a funding rate update for another liveness period. So the disputer's cost should be proportional to the proposer's CoC. Their reward could also be similar to the proposer's reward because they are performing a similar function to the proposer.

**Comment by nicholaspai** [comment]
### Some more updates to the discussion:

## Another way to think about the profit from corruption after talking with @hlambur :
- Imagine the current funding rate is F, and F is off from the true funding rate by some error % E. Let's assume conservatively that in the worst case E = 200%/year. Let's also assume that you are a sponsor with debt outstanding and it just so happens that you benefit by F staying as it is. One way you would profit from this would be to keep disputing newly proposed funding rates until the DVM forcibly changed the funding rate. The DVM in the worst case resolves in 72 hours after the first dispute, and you have just under 2 hours to trigger the first dispute. So, you can delay an update to F for 74 hours max.
- Breaking down your potential profit per hour: 200 % / year / 360 days / 24 hours ~ 2% / hour. So 2 %/hour * 74 hours = 1.48% profit on your position's debt.
- Your cost is calculated by the minimum amount of dispute bonds you'd need to pay to delay a funding rate update for 74 hours. The way to do this is to dispute a pending funding rate right before its 2 hour liveness expires. So, 74 hours / 2 hours = 37 updates and proposal bonds.
- So, 0.0148 / 37 = 0.0004, or 0.04% (4 basis points) is the cost of one dispute bond for you to break even.

## It's interesting to note that this dispute bond is the same that we calculated above in section Q6. We can refactor the math to show that we effectively calculated the 2 hour profit for a 200%/year attack: 
- Potential profit from delaying funding rate update = 
- (200 %/year / 360 days / 24 hours * 74 hours / 37 updates) = 
- (200 %/year / 360 days / 24 hours * 2 hours/update) =
- (0.56 %/day / 24 hours * 2 hours/update) = 
- (0.0231 % / hour * 2 hours / update) =
- **0.0463% bond per update** 

## @hlambur also touched on other topics:
-we should NOT constrain the range of possible funding rates, because there might be situations in which we want extreme funding rates to more quickly incentivize sponsor behavior.
- one way to think about the Funding Rate proposer's reward is to consider their desired IRR. 
- the proposer bond should be denominated in token currency, because the token debt outstanding is the potential corrupted value
- the proposer reward should be denominated in collateral currency, to simplify logic and implementation since we already charge regular fees in this currency
