### ISSUE TITLE
Refactor Perpetual contract inheritance tree

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2085]
**Why**

TODO: Explain why inheritance tree is muddled right now.

**How**

Proposed inheritance tree, listed from parent to child:
- `EmergencyShutdownable` (terrible name admittedly): Stores an emergency shutdown timestamp and price and provides modifiers that determine whether a contract is in the shutdown state or not. Does not implement the logic for once a contract is shutdown, leaves that to child contracts.
- `FundingRateApplier`: Same as current but removes the public `applyFundingRate()` method as this should be left for child contracts and protected with `nonReentrant` and `notEmergencyShutdown` modifiers. Will require an additional testing contract to be built to test the `_applyFundingRate()` functionality.
- `PositionManager` is `FundingRateApplier`, `EmergencyShutdownable`: Implements `emergencyShutdown()`, `settleEmergencyShutdown()`, `applyFundingRate()`
- `Liquidatable` is `PositionManager`: same as current

New Contracts:
- `EmergencyShutdownable`
- `MockFundingRateApplier`: implements `applyFundingRate()` so that we can test `FundingRateApplier` in isolation.

**Resolution**

Unit tests should be built. Bytecode size of `PerpetualLib.sol contract should be under limit.

**Difficulty Score [1-10]**

This is a measure of the amount of developer time this task will require to be completed. Note: this should include design and planning time in addition to implementation time. The scale is not linear:

- 4: ~2 hours

**Comment by chrismaree** [comment]
This is a good refactor & something that is required now that the `fundingRateApplier` needs to check that the contract is not emergency shutdown before updating the `cumulativeFundingRateMultiplier`. 

As you propose, by keeping the `EmergencyShutdownable` and `FundingRateApplier` in the same level in the inheritance tree we can implement the `applyFundingRate` within the `PositionManager` to decouple this dependency.

One other point of contention that will also require a refactor is that both `FeePayer` and `FundingRateApplier` are `Testable` but are at the same level in the inheritance tree. This results in an error in solidity due to duplicated constructor params. Right now the solution implemented in https://github.com/UMAprotocol/protocol/pull/2084 is to simply instantiate an instance of `Timer` within the `FundingRateApplier` to enable the current time to be queried, without messing with the inheritance structure. This is not super clean and it might warrant a further refactor, in a similar vein to what this issue describes.

**Comment by nicholaspai** [comment]
Closed by #2084
