### ISSUE TITLE
Discussion: Should dev mining rewards be paid to expired EMPs with liquidity

### ISSUE THREAD

**Issue by daywiss** [UMAprotocol/protocol#2265]
**Why**

Dev mining rewards essentially split a pot of UMA pro rata every week across whitelisted EMPs that contain liquidity. Some EMPs may be expired, but still contain liquidity. As time goes, there may be more contracts which expire as well and these compete with active EMPs. The open question is, should be continue to split the rewards across expired and unexpired EMPs? Is there a better way to handle this situation?

**How**
Looking for a yes no or other type of answer
- Yes: emps should be rewarded in perpetuity regardless of expiry since they contain liquidity
- No: once a contract expires stop paying rewards to it. 
- Other: Perhaps expired contracts could be considered on a case by case basis to justify expired rewards, etc

Personally I would lean towards NO, its simple, it incentivizes creation of new EMPs and computationally it naturally limits the number of contracts we compute rewards for. If anyone has any additional thoughts would love to hear. 

**Resolution**

Would be nice to get resolution before next payout!

**Comment by smb2796** [comment]
I'm also in the NO camp. @daywiss I agree on your point that the purpose of developer mining is to incentivize new contracts. I'd also add:

Dev mining also is trying to encourage developers to run dapp mining and liquidity mining programs with received rewards. After expiry, dapp mining is impossible to continue, and liquidity mining is somewhat pointless.

Also - if I was a contract deployer and minted a large initial position using WETH, I might not ever redeem my tokens because I'll get free yield from dev mining while maintaining my collateral exposure. I don't think there is any advantage to rewarding this type of behavior.

**Comment by daywiss** [comment]
No was unanimous. We can remove any expired emps from next weeks rewards. There are still some details around rewarding emps which expire within the week rewards are calculated but for now I think its OK if we just let those participate through the end of the week.
