### ISSUE TITLE
Improve reliability of migration against mainnet

### ISSUE THREAD

**Issue by rawfalafel** [UMAprotocol/protocol#333]
Two options we can take:
1. Add a nonce tracker in our provider, similar to this: https://github.com/MetaMask/provider-engine/blob/87067488ccd8a4afb27739c8f925467b7de5264c/subproviders/nonce-tracker.js
2. Run our own private node

In addition, this should confirm that the fix resolves our issue. We might be able to cheaply simulate it on mainnet with a script that iterates over a series of simple transactions.

**Comment by kowalski** [comment]
Small unsolicited hint: I can see you guys are using Infura over http for mainnet migrations. 
Infura has load balancer and no mechanism of session stickiness. This causes requests to be routed to different nodes. Truffle creates newBlock filter and than queries for it's status. The mechanism brakes if there is more than one node involved, because the queried node has no knowledge about the filterId it's being queried for.

The easiest way to circumvent this problem is to use Infura over websocket connection. This way you'll have a persistent connection to one specific node so it doesn't loose the context.
