### ISSUE TITLE
Allow data for EOA

### ISSUE THREAD

**Issue by mktcode** [UMAprotocol/protocol#4103]
https://github.com/UMAprotocol/protocol/blob/f9448bd12c30e03a31fd40cbf1069aff671eff5f/packages/core/contracts/zodiac/OptimisticGovernor.sol#L206-L208

A simple ETH transfer to an EOA can contain data. Nothing wrong with that afaik. I used that in a project of mine to add notes to transactions. Any reason it needs to be blocked here?

**Comment by mrice32** [comment]
Sorry we've been slow to respond to this! The reason this is blocked is two-fold:
1. This isn't common in oSnap governance transactions, because the data would not show up in the transaction one would see in etherscan. It would show up as an internal transaction, so a user would have to be pretty sophisticated to dig up this data. It wouldn't be as trivial as clicking a button in etherscan to display txn data as UTF-8.
2. It's more likely than not that when this is done in a governance transaction (because of 1) that this is done in error. So this is meant to catch errors where a transaction did something that wasn't intended by the author.

It's a tradeoff made to slightly improve safety at the cost of some flexibility.

**Comment by mrice32** [comment]
Feel free to reopen if you disagree or think a new version should include this feature!
