### ISSUE TITLE
Address solidity-coverage exception with MultiRole call

### ISSUE THREAD

**Issue by rawfalafel** [UMAprotocol/protocol#456]
This issue tracks the fact that `solidity-coverage` mysterious throws an exception when `MultiRole` roles are created in the constructor instead of [in a separate function](https://github.com/UMAprotocol/protocol/blob/9fa9efe9eca1c8870658a62a961c7c91c4073ee7/core/contracts/Registry.sol#L127). 

Other imperfect workarounds that seem to work:
* Modifying `_createSharedRole` and `_createExclusiveRole` into public functions
* Commenting out `*RoleMembership.init` function calls when creating shard role.

**Comment by ptare** [comment]
I think your first proposal is reasonable.

It would mean that anyone could create new roles, but creating new, unused roles doesn't cause any security flaws. Since roles are only kept in maps, unused roles also wouldn't require extra computation when checking permissions. The creator of those roles would pay gas for storing them.

Not perfect, but might be better than initializeOnce functions in every contract.

**Comment by ptare** [comment]
@mrice32 Thoughts?

Another option could be to use a preprocessing step to modify the code when running coverage to change `_createSharedRole` and _createExclusiveRole` into public methods, but leave them internal in production. (so like a C #define to create a debug build). We'd have to do some text processing in the script coverage.sh.
