### ISSUE TITLE
Low priority documentation issue: node version instructions

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#795]
[Prerequisites](https://github.com/UMAprotocol/protocol/blob/master/documentation/tutorials/prerequisites.md) page states that "Install nodejs v11.15.0 and ensure that npm is installed along with it." 

Just FYI I was able to install node prereqs (`cd protocol/ && npm install`), compile solidity contracts (`truffle compile`), and pass all of tests** (`truffle test --network local`) while using the latest stable version of node: 

```
$ node -v
v13.3.0
$ npm -v
6.13.1
```

My question is: is there a reason why you are soft-forcing the node version to be 11.15.0? 

** The only tests I failed related to  "Intrinio" which was expected as I skipped the "deploy your own price feed" section.

**Comment by mrice32** [comment]
Thanks for raising this issue!

We've had issues with other versions in the past due to some of our npm dependencies. For that reason, we pinned our ci jobs to `11.X.X`. Since we only run automated tests on `11.X.X`, we only *actively* guarantee compatibility with that version rather than `latest`.

We haven't messed with our node version in a while, though. If everything works with `latest`, I think it would be a good idea to change the version we use for ci and change the guidance in the docs, but I think the docs *should* correspond to whatever we do in ci.

You don't have an intrinio API key, so those tests are expected to fail, but that should also be documented :).

**Comment by mrice32** [comment]
I put up #798 to change the node version in ci and some of our dApp dependencies fail to install. We can probably fix this, but we'll need to debug.

**Comment by ptare** [comment]
This task is done.
